// build-config.js — runs at Vercel build time to generate supabase-config.js
// Set SUPABASE_URL and SUPABASE_ANON_KEY in: Vercel Dashboard → Project → Settings → Environment Variables

const fs = require('fs');

const url  = process.env.SUPABASE_URL;
const key  = process.env.SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error('❌  SUPABASE_URL and SUPABASE_ANON_KEY must be set as environment variables.');
  process.exit(1);
}

const content = `// Auto-generated by build-config.js — do not edit manually
const SUPABASE_URL      = '${url}';
const SUPABASE_ANON_KEY = '${key}';
const supabaseClient    = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
`;

fs.writeFileSync('supabase-config.js', content);
console.log('✅  supabase-config.js generated successfully.');
